#!/bin/bash

./curl /1.0/clean/address <<EOF
[
    {
        "id": "foo",
        "original-address": "г. Москва, Варшавское шоссе, 37"
    },
    {
        "id": "bar",
        "original-address": "г. Новосибирск, ул. Жуковского, 100/4"
    }
]
EOF
