#!/bin/bash
set -e

if [ -z "$TOKEN" -o -z "$AUTH" ]
then
    test -f tkn.txt
    TOKEN="$(cat tkn.txt)"
    test -f auth.txt
    AUTH="$(cat auth.txt)"
fi

set -u

API=https://otpravka-api.pochta.ru

data=$(</dev/stdin)

jq=$(command -v jq || command -v json_pp || command -v cat)

verb=${1:-POST}
target="$2"

if [ -t 1 ]
then
    filter=$jq
    echo $data | $jq
    echo "$verb $target"
	echo
else
    filter=cat
fi

curl -s --dump-header /dev/stderr \
-H "X-User-Authorization: Basic $AUTH" \
-H "Authorization: AccessToken $TOKEN" \
-H "Content-Type: application/json;charset=UTF-8" \
-H "Accept: application/json;charset=UTF-8" \
--request $verb \
--data "$data" \
$API$target | $filter
