#!/bin/bash
set -e -u

test -f tkn.txt
test -f auth.txt

TKN="$(cat tkn.txt)"
AUTH="$(cat auth.txt)"
API=https://otpravka-api.pochta.ru

data=$(</dev/stdin)

jq=$(command -v jq || command -v json-tool || command -v cat)

if [ -t 1 ]
then
    filter=$jq
    echo $data | $jq
    echo "POST $1"
	echo
else
    filter=cat
fi

curl -s \
-H "X-User-Authorization: Basic $AUTH" \
-H "Authorization: AccessToken $TKN" \
-H "Content-Type: application/json;charset=UTF-8" \
-H "Accept: application/json;charset=UTF-8" \
--request POST \
--data "$data" \
$API$1 | $filter
